# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class DashboardControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/admin/dashboard_controller.rb"
  end
end
