# frozen_string_literal: true

# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class InviteCodesControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/admin/invite_codes_controller.rb"
  end
end
