# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class UsersControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/admin/users_controller.rb"
  end
end
