# frozen_string_literal: true

# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AgentPersonasControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/agent_personas_controller.rb"
  end
end
