# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ApplicationControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/application_controller.rb"
  end
end
