# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class BrainDumpsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/brain_dumps_controller.rb"
  end
end
