# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class CodemapMonitorControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/codemap_monitor_controller.rb"
  end
end
