# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class DecisionsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/decisions_controller.rb"
  end
end
