# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class FactoryLoopsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/factory_loops_controller.rb"
  end
end
