# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class LearningProposalsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/learning_proposals_controller.rb"
  end
end
