# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class MarketingControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/marketing_controller.rb"
  end
end
