# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class NotificationsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/notifications_controller.rb"
  end
end
