# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class PipelineDashboardControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/pipeline_dashboard_controller.rb"
  end
end
