# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class PreviewsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/previews_controller.rb"
  end
end
