# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ProfilesControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/profiles_controller.rb"
  end
end
