# frozen_string_literal: true

# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SavedLinksControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/saved_links_controller.rb"
  end
end
