# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SystemControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/system_controller.rb"
  end
end
