# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ZerobitchControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/zerobitch_controller.rb"
  end
end
