# frozen_string_literal: true

# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AuthenticationTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/concerns/authentication.rb"
  end
end
