# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class GatewayConfigPatchableTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/concerns/gateway_config_patchable.rb"
  end
end
