# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AgentActivityIngestionServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/agent_activity_ingestion_service.rb"
  end
end
