# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class CodemapBroadcasterTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/codemap_broadcaster.rb"
  end
end
