# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class DebateReviewServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/debate_review_service.rb"
  end
end
