# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class EmojiShortcodeNormalizerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/emoji_shortcode_normalizer.rb"
  end
end
