# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ExternalNotificationServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/external_notification_service.rb"
  end
end
