# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class FactoryEngineServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/factory_engine_service.rb"
  end
end
