# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class HeartbeatAlertGuardTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/heartbeat_alert_guard.rb"
  end
end
