# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class LearningEffectivenessServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/learning_effectiveness_service.rb"
  end
end
