# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class LobsterRunnerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/lobster_runner.rb"
  end
end
