# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ModelCatalogServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/model_catalog_service.rb"
  end
end
