# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class NightshiftEngineServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/nightshift_engine_service.rb"
  end
end
