# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class NightshiftSyncServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/nightshift_sync_service.rb"
  end
end
