# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OpenclawGatewayClientTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/openclaw_gateway_client.rb"
  end
end
