# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OpenclawModelsServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/openclaw_models_service.rb"
  end
end
