# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OpenclawWebhookServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/openclaw_webhook_service.rb"
  end
end
