# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OriginDeliveryServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/origin_delivery_service.rb"
  end
end
