# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OutcomeEventChannelTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/outcome_event_channel.rb"
  end
end
