# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SessionCostAnalyticsTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/session_cost_analytics.rb"
  end
end
