# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SocialMediaPublisherTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/social_media_publisher.rb"
  end
end
