# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SubAgentOutputContractTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/sub_agent_output_contract.rb"
  end
end
