# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TranscriptParserTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/transcript_parser.rb"
  end
end
