# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TranscriptWatcherTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/transcript_watcher.rb"
  end
end
