# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TranscriptArchiveServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/transcript_archive_service.rb"
  end
end
