# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ValidationSuggestionServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/validation_suggestion_service.rb"
  end
end
