# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ValidationRunnerServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/validation_runner_service.rb"
  end
end
