# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AgentMessagesControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/agent_messages_controller.rb"
  end
end
