# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class LearningEffectivenessControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/learning_effectiveness_controller.rb"
  end
end
