# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class Api::V1::LearningProposalsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/learning_proposals_controller.rb"
  end
end
