# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ModelLimitsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/model_limits_controller.rb"
  end
end
