# frozen_string_literal: true

# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class Api::V1::NotificationsControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/notifications_controller.rb"
  end
end
