# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class PipelineControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/pipeline_controller.rb"
  end
end
