# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SavedLinksControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/saved_links_controller.rb"
  end
end
