# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class SwarmIdeasControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/swarm_ideas_controller.rb"
  end
end
