# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TaskTemplatesControllerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/api/v1/task_templates_controller.rb"
  end
end
