# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AutoReviewServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/auto_review_service.rb"
  end
end
