# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ClawRouterServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/claw_router_service.rb"
  end
end
