# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class ContextCompilerServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/context_compiler_service.rb"
  end
end
