# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class OrchestratorTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/orchestrator.rb"
  end
end
