# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class QdrantClientTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/qdrant_client.rb"
  end
end
