# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TriageServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/pipeline/triage_service.rb"
  end
end
