# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AutoScalerTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/zerobitch/auto_scaler.rb"
  end
end
