# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class DockerServiceTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/zerobitch/docker_service.rb"
  end
end
