# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class FleetTemplatesTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/zerobitch/fleet_templates.rb"
  end
end
