# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class MetricsStoreTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/zerobitch/metrics_store.rb"
  end
end
