class ProfilesController < ApplicationController
  def show
    @user = current_user
    @api_token = current_user.api_tokens.find_or_create_by!(name: "Clawdbot") do |token|
      # Token is auto-generated by the model
    end
  end

  def update
    @user = current_user

    if params[:user][:remove_avatar] == "1"
      @user.avatar.purge
    end

    if @user.update(profile_params)
      redirect_to settings_path, notice: "Profile updated successfully."
    else
      render :show, status: :unprocessable_entity
    end
  end

  def regenerate_api_token
    @api_token = current_user.api_tokens.find_by(name: "Clawdbot")
    @api_token&.destroy
    @api_token = current_user.api_tokens.create!(name: "Clawdbot")
    redirect_to settings_path, notice: "API token regenerated."
  end

  private

  def profile_params
    params.expect(user: [ :email_address, :avatar ])
  end
end
