# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class TaskPipelineManagementTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/controllers/concerns/api/task_pipeline_management.rb"
  end
end
