# Auto-generated by nightly-bug-tracker.sh
require "test_helper"

class AuditableTaskTest < ActiveSupport::TestCase
  test "needs coverage" do
    skip "TODO: implement tests for app/services/zeroclaw/auditable_task.rb"
  end
end
